env:
  browser: true
  es2021: true
extends:
  - standard
  - "next/core-web-vitals"
  - "plugin:tailwindcss/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - simple-import-sort
  - "@typescript-eslint"
rules:
  "simple-import-sort/imports": "error"
  jsx-quotes: ["error", "prefer-single"]
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": "error"
  "react/prop-types": "off"
