import fs from 'fs'
import type { GetStaticPaths, GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import path from 'path'

import { Markdown } from '~/components/markdown'

type Params = {
  id: string
}

type Props = {
  id: string
  contents: string
}

export const getStaticPaths: GetStaticPaths<Params> = async () => {
  const postsDirectory = path.join(process.cwd(), 'posts')

  const fileNames = fs.readdirSync(postsDirectory)

  const paths = fileNames.map((fileName) => ({
    params: {
      id: fileName.replace(/\.md$/, '')
    }
  }))

  return {
    paths,
    fallback: false
  }
}

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
  if (!params?.id) throw new Error('')
  const postsDirectory = path.join(process.cwd(), 'posts')

  const fullPath = path.join(postsDirectory, `${params.id}.md`)
  const fileContents = fs.readFileSync(fullPath, 'utf8')

  return {
    props: {
      id: params.id,
      contents: fileContents
    }
  }
}

const Note: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>{props.id}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main>
        <div css={{
          boxSizing: 'border-box',
          maxWidth: 900,
          width: '100%',
          marginLeft: 'auto',
          marginRight: 'auto',
          marginTop: 32,
          marginBottom: 32,
          paddingLeft: 24,
          paddingRight: 24
        }}>
          <div css={{
            background: '#fff',
            '-webkit-transition': 'box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms',
            transition: 'box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms',
            borderRadius: '6px',
            border: '1px solid',
            borderColor: 'rgba(0,0,0,0.12)',
            paddingLeft: 8,
            paddingRight: 8
          }}>
            <Markdown>{props.contents}</Markdown>
          </div>
        </div>
      </main>
    </>
  )
}

export default Note
