import Head from 'next/head'

export default function Root () {
  return (
    <>
      <Head>
        <title></title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main>
        <div css={{ height: 'calc(100vh - 4px)' }}>
          <iframe src='https://chromedino.com/' width='100%' height='100%' loading='lazy'
            css={{ border: 0 }}
          ></iframe>
        </div>
      </main>
    </>
  )
}
